apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  namespace: prod

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: laravel
  template:
    metadata:
      labels:
        app.kubernetes.io/name: laravel
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: laravel-nginx
      containers:
        - name: nginx
          image: nginx:1.26
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
          volumeMounts:
            - name: nginx-config
              subPath: nginx.conf
              mountPath: /etc/nginx/nginx.conf
              readOnly: true
        - name: app
          image: ghcr.io/champalab/malaythong:5640ac0fdc5efa836d78b00dfd61d5faf186b2e6
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: laravel-env
